# Generated by Django 3.2.3 on 2021-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='paises',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
